import {
    API_URL,
    API_URL_API,
    API_URL_AUT,
    API_URL_PDF,
    API_URL_PDF_DOC,
    API_URL_ASO,
    API_URL_DOCEN,
    API_URL_INT_ASOC,
    API_URL_NOT, 
    API_URL_SLID,       
    url_escuela1,   
    getNews,    
    url_slider,   
    url_logos,
    API_KEY,
  } from "@env";
  
  export default {    
    API_URL,
    API_URL_API,
    API_URL_AUT,
    API_URL_PDF,
    API_URL_PDF_DOC,
    API_URL_ASO,
    API_URL_DOCEN,
    API_URL_INT_ASOC,
    API_URL_NOT,    
    API_URL_SLID,       
    url_escuela1,   
    getNews,    
    url_slider,   
    url_logos,
    API_KEY,
  };
  